name: Deploy to Fly
on: [push]
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: checkout
        uses: actions/checkout@v3
      - name: flyctl setup
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: create env file
        run: |
          touch .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
      - name: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}